// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukulyeurcjumawqpmgtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdWx5ZXVyY2p1bWF3cXBtZ3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDEwNjEsImV4cCI6MjA3MjIxNzA2MX0.zpuBUKy5j7yvAlXyUBMbBkTofDwvnfNSn1yjmRsMTLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});